version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app  # (ec2)인스턴스에서 파일이 저장될 위치
    
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: root
