# logging 설정
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: debug

# console 색상
spring:
  output:
    ansi:
      enabled: always
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.gmail.com
    port: 587
    username: woori.memory@gmail.com
    password: pfzkjixaaddokvnm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# 오류 처리
server:
  error:
    include-exception: true
    include-stacktrace: always

  #port 설정
  port: 8080